export const personas = [
  {
    id: 1,
    tipo: "usuario",
    nombre: "Juan Pérez",
    documento: "30567890",
    fechaNacimiento: "1990-05-15",
    domicilio: "Av. Siempre Viva 742",
    telefono: "1123456789",
    genero: "Masculino",
    email: "juan.perez@example.com",
    discapacidad: "No",
    coberturaSocial: "OSDE",
    reclamo: {
      tipo: "Cobertura médica",
      descripcion: "Problema con la autorización de una cirugía",
      estado: "Pendiente",
      fechaReclamo: "2024-02-15",
    },
  },
  {
    id: 2,
    tipo: "trabajador",
    nombre: "María González",
    documento: "28456789",
    fechaNacimiento: "1985-10-23",
    domicilio: "Calle Falsa 123",
    telefono: "1134567890",
    genero: "Femenino",
    email: "maria.gonzalez@example.com",
    discapacidad: "No",
    coberturaSocial: "Swiss Medical",
    lugarTrabajo: "Hospital Central",
    agrupamiento: "Administrativo",
    contratacion: "Planta Permanente",
    disciplina: "Enfermería",
    observaciones: "Turno nocturno",
    reclamo: {
      tipo: "Condiciones laborales",
      descripcion: "Solicita revisión de turnos nocturnos excesivos",
      estado: "En proceso",
      fechaReclamo: "2024-01-10",
    },
  },
  {
    id: 3,
    tipo: "usuario",
    nombre: "Carlos López",
    documento: "32987654",
    fechaNacimiento: "1995-08-12",
    domicilio: "San Martín 456",
    telefono: "1145678901",
    genero: "Masculino",
    email: "carlos.lopez@example.com",
    discapacidad: "Sí",
    coberturaSocial: "PAMI",
    reclamo: {
      tipo: "Atención médica",
      descripcion: "Falta de atención prioritaria para discapacitados",
      estado: "Resuelto",
      fechaReclamo: "2023-12-20",
    },
  },
  {
    id: 4,
    tipo: "trabajador",
    nombre: "Ana Fernández",
    documento: "DNI 27345678",
    fechaNacimiento: "1980-03-05",
    domicilio: "Belgrano 789",
    telefono: "1156789012",
    genero: "Femenino",
    email: "ana.fernandez@example.com",
    discapacidad: "No",
    coberturaSocial: "IOMA",
    lugarTrabajo: "Clínica Privada Norte",
    agrupamiento: "Médico",
    contratacion: "Monotributista",
    disciplina: "Cardiología",
    observaciones: "Especialista en urgencias",
  },
  {
    id: 5,
    tipo: "usuario",
    nombre: "Sofía Ramírez",
    documento: "DNI 31876543",
    fechaNacimiento: "2000-07-20",
    domicilio: "Rivadavia 1020",
    telefono: "1167890123",
    genero: "Femenino",
    email: "sofia.ramirez@example.com",
    discapacidad: "No",
    coberturaSocial: "Medicus",
  },
  {
    id: 6,
    tipo: "trabajador",
    nombre: "Gustavo Peralta",
    documento: "DNI 26678901",
    fechaNacimiento: "1975-06-30",
    domicilio: "Mitre 150",
    telefono: "1178901234",
    genero: "Masculino",
    email: "gustavo.peralta@example.com",
    discapacidad: "No",
    coberturaSocial: "OSDE",
    lugarTrabajo: "Sanatorio Sur",
    agrupamiento: "Técnico",
    contratacion: "Contratado",
    disciplina: "Radiología",
    observaciones: "Especialista en resonancias",
  },
  {
    id: 7,
    tipo: "usuario",
    nombre: "Lucas Benítez",
    documento: "DNI 33123456",
    fechaNacimiento: "1998-09-14",
    domicilio: "Sarmiento 300",
    telefono: "1189012345",
    genero: "Masculino",
    email: "lucas.benitez@example.com",
    discapacidad: "Sí",
    coberturaSocial: "PAMI",
  },
  {
    id: 8,
    tipo: "trabajador",
    nombre: "Verónica Díaz",
    documento: "DNI 25567890",
    fechaNacimiento: "1970-11-10",
    domicilio: "Entre Ríos 450",
    telefono: "1190123456",
    genero: "Femenino",
    email: "veronica.diaz@example.com",
    discapacidad: "No",
    coberturaSocial: "IOMA",
    lugarTrabajo: "Hospital del Norte",
    agrupamiento: "Médico",
    contratacion: "Residente",
    disciplina: "Pediatría",
    observaciones: "Turnos de 12 horas",
  },
  {
    id: 9,
    tipo: "usuario",
    nombre: "Fernando Castro",
    documento: "DNI 34234567",
    fechaNacimiento: "2002-01-25",
    domicilio: "Corrientes 750",
    telefono: "1201234567",
    genero: "Masculino",
    email: "fernando.castro@example.com",
    discapacidad: "No",
    coberturaSocial: "Medife",
  },
  {
    id: 10,
    tipo: "trabajador",
    nombre: "Patricia Muñoz",
    documento: "DNI 24567890",
    fechaNacimiento: "1965-04-18",
    domicilio: "Santa Fe 999",
    telefono: "1212345678",
    genero: "Femenino",
    email: "patricia.munoz@example.com",
    discapacidad: "No",
    coberturaSocial: "Swiss Medical",
    lugarTrabajo: "Hospital General",
    agrupamiento: "Administrativo",
    contratacion: "Planta Permanente",
    disciplina: "Gestión Hospitalaria",
    observaciones: "Encargada de recursos humanos",
  },
];
